sudo: true
language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
script:
  # travis default rust test script
  - cargo build --verbose
  - cargo test --verbose
  # benches use the test feature which is only available on nightly
  # run benches once per build to detect performance regressions
  - if [ "$TRAVIS_RUST_VERSION" = "nightly" ] ; then
     cargo bench --verbose;
    fi
env:
  global:
    - secure: "fsFfiix3y3+72RHvtPB1S5CnYHCCWI1taqozx24eYlLykOctYLChyPTAfh/Xnm0WhG8tHSDO5WSz7b+v/NPrA308HcwTNl9PPeFGj3dTV85xWABHvJExWG1SnPQJ43EdZJe4Z4P9AJezXCkYZ8sATvzJmWtlkLUZN4aXqFxRapXguZmLCP6ZMSXYo/WJ3P4gfGTptga9h4des7rqGf21CmYr349sA9s8YVL6QZ35jTJj06syoZVpAgOKxM2zYE5XMHOcSvnM7p9+D+OycT7EXytryZi5O9nukbGElVA6ZwIf1jM8bZbFXe/oZsaqFy9q8rrZM3bEEAwS02j/EO1BGPIis6eLfdfZ2YCJCTWulSFDTKfgObBwVvLXKXSBk1WtfK1qPMoaMIw+ol48EW2WsoAMYMUWlmyBaqSumabwXgrLbvVFGaCGRTuKlZEaSRdBusQfdA8BHaAGO3204DHG7uh+aDWB0JN0I4gBC/92qI89C6n5NmhfCpPPTK8zK9MG0EIGTuC0u4csbOIBFQG5hSP6kYyMOvo9Js40qRy6t+JLlAnG3koHR3Bgz+y8Vmkc7itJcnqc45Urt4cosmTEyCrnrBvnO3LHJDHjknFe8BFMdsJSnvZLNOhbM3mI1rgYUd9iEf/IwFPcCpcOW9SUsVJrGNKe8ekwGtz/ZYE00pI="
# after success build rust documentation and push it to gh-pages branch
# only do this for the stable branch (once per build)
after_success: |
  if [ "$TRAVIS_RUST_VERSION" = "stable" ] ; then
    cargo doc --no-deps && \
    sudo pip install ghp-import && \
    ghp-import -n target/doc && \
    git push -qf https://${GITHUB_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages
  fi
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -qq libatlas-base-dev
